CREATE TYPE org_kind          AS ENUM ('cliente', 'fabricante');
CREATE TYPE user_role         AS ENUM ('operador', 'tecnico', 'assistencia');
CREATE TYPE incident_severity AS ENUM ('baixa', 'media', 'critica');
CREATE TYPE incident_status   AS ENUM ('recebida', 'em_analise', 'resolvida');
CREATE TYPE attachment_kind   AS ENUM ('foto', 'audio', 'video');

CREATE TABLE organizations (
    id         uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    name       text NOT NULL,
    kind       org_kind NOT NULL,
    created_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE users (
    id              uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    organization_id uuid NOT NULL REFERENCES organizations (id),
    name            text NOT NULL,
    email           text NOT NULL,
    password_hash   text NOT NULL,
    role            user_role NOT NULL,
    created_at      timestamptz NOT NULL DEFAULT now()
);
CREATE UNIQUE INDEX users_email_key ON users (lower(email));
CREATE INDEX users_organization_idx ON users (organization_id);

CREATE TABLE machines (
    id              uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    organization_id uuid NOT NULL REFERENCES organizations (id),
    serial_number   text NOT NULL UNIQUE,
    model           text NOT NULL,
    created_at      timestamptz NOT NULL DEFAULT now(),
    UNIQUE (id, organization_id)  -- target for the composite FK below
);
CREATE INDEX machines_organization_idx ON machines (organization_id);

CREATE TABLE incidents (
    id              uuid PRIMARY KEY,  -- generated by the client
    organization_id uuid NOT NULL,     -- owner of the machine, kept consistent by the FK
    machine_id      uuid NOT NULL,
    author_id       uuid NOT NULL REFERENCES users (id),
    description     text NOT NULL DEFAULT '',  -- may be empty if reported by voice
    severity        incident_severity NOT NULL,
    status          incident_status NOT NULL DEFAULT 'recebida',
    latitude        double precision,
    longitude       double precision,
    accuracy_m      real,
    reported_at     timestamptz NOT NULL,      -- device clock, when it was created offline
    created_at      timestamptz NOT NULL DEFAULT now(),  -- server insertion time
    updated_at      timestamptz NOT NULL DEFAULT now(),
    FOREIGN KEY (machine_id, organization_id)
        REFERENCES machines (id, organization_id),
    CHECK ((latitude IS NULL) = (longitude IS NULL)),
    CHECK (latitude  BETWEEN -90  AND 90),
    CHECK (longitude BETWEEN -180 AND 180),
    CHECK (accuracy_m >= 0)
);
-- incremental sync and org isolation, keyset-paginated on (updated_at, id)
CREATE INDEX incidents_org_sync_idx ON incidents (organization_id, updated_at, id);
CREATE INDEX incidents_machine_idx  ON incidents (machine_id, created_at DESC);
-- support triage queue: open incidents, most severe first
CREATE INDEX incidents_triage_idx   ON incidents (severity DESC, created_at)
    WHERE status <> 'resolvida';

CREATE TABLE attachments (
    id           uuid PRIMARY KEY,  -- generated by the client, idempotent upload
    incident_id  uuid NOT NULL REFERENCES incidents (id) ON DELETE CASCADE,
    kind         attachment_kind NOT NULL,
    content_type text NOT NULL,
    storage_key  text NOT NULL UNIQUE,
    size_bytes   bigint NOT NULL CHECK (size_bytes > 0),
    created_at   timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX attachments_incident_idx ON attachments (incident_id);

CREATE TABLE incident_updates (
    id          uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    incident_id uuid NOT NULL REFERENCES incidents (id) ON DELETE CASCADE,
    author_id   uuid NOT NULL REFERENCES users (id),
    message     text,
    new_status  incident_status,
    created_at  timestamptz NOT NULL DEFAULT now(),
    CHECK (message IS NOT NULL OR new_status IS NOT NULL)
);
CREATE INDEX incident_updates_incident_idx ON incident_updates (incident_id, created_at);

CREATE TABLE devices (
    id           uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    user_id      uuid NOT NULL REFERENCES users (id) ON DELETE CASCADE,
    fcm_token    text NOT NULL UNIQUE,
    last_seen_at timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX devices_user_idx ON devices (user_id);

CREATE TABLE refresh_tokens (
    id         uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    user_id    uuid NOT NULL REFERENCES users (id) ON DELETE CASCADE,
    token_hash bytea NOT NULL UNIQUE,  -- SHA-256 of the token, never the token itself
    expires_at timestamptz NOT NULL,
    revoked_at timestamptz,
    created_at timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX refresh_tokens_user_idx ON refresh_tokens (user_id);

-- Any change to an incident bumps updated_at, so updated_since can't miss it.
CREATE FUNCTION incidents_touch() RETURNS trigger LANGUAGE plpgsql AS $$
BEGIN
    NEW.updated_at := now();
    RETURN NEW;
END $$;

CREATE TRIGGER incidents_touch_updated_at
    BEFORE UPDATE ON incidents
    FOR EACH ROW EXECUTE FUNCTION incidents_touch();

-- A new update applies its status (if any) and, via the trigger above, bumps updated_at.
CREATE FUNCTION incident_updates_apply() RETURNS trigger LANGUAGE plpgsql AS $$
BEGIN
    UPDATE incidents
       SET status = COALESCE(NEW.new_status, status)
     WHERE id = NEW.incident_id;
    RETURN NULL;
END $$;

CREATE TRIGGER incident_updates_after_insert
    AFTER INSERT ON incident_updates
    FOR EACH ROW EXECUTE FUNCTION incident_updates_apply();

CREATE FUNCTION attachments_touch_incident() RETURNS trigger LANGUAGE plpgsql AS $$
BEGIN
    UPDATE incidents SET updated_at = now() WHERE id = NEW.incident_id;
    RETURN NULL;
END $$;

CREATE TRIGGER attachments_after_insert
    AFTER INSERT ON attachments
    FOR EACH ROW EXECUTE FUNCTION attachments_touch_incident();